services:
  app:
    build: .
    privileged: true
    working_dir: /app
    command: "python main.py"
    volumes:
      - ./config:/app/config
      #- /etc/localtime:/etc/localtime:ro
      #- /run/udev:/run/udev:ro
