[constants]
mqtt_address = "129.169.48.173"
current_name = "3D_Printing"
order = "RL10001"
trolleyList = ["Trolley_2"]

[influxdb]
url = "http://129.169.48.173:8086"
token = "robot-lab-2023"
org = "Robot_Lab"
