[constants]
mqtt_address = "mqtt.docker.local"
current_name = "Supplier"
order = "RL10001"
trolleyList = ["Trolley_1", "Trolley_2", "Trolley_3"]

[influxdb]
url = "http://timeseries-db.docker.local:8086"
token = "voom-random-intial-tocken-akheen484789fjhfja=006/54"
org = "Supplier_Lab"
